CFLAGS = -Wall -std=c99 -g

all:
#	gcc -Wall -std=c99 -g -o size size.c
#	./size
#	gcc -Wall -std=c99 -g -o ex1 ex1.c
#	./ex1
	gcc -Wall -std=c99 -g -o walltime walltime.c
	./walltime
clean:
	rm -f ./size
	rm -f ./ex1
	rm -f ./walltime
