CC = g++
CFLAGS = -std=gnu++14 -Wall


all:
	$(CC) $(CFLAGS) -o matrix_class1 matrix_class1.cpp
	$(CC) $(CFLAGS) -o matrix_class3 matrix_class3.cpp
	$(CC) $(CFLAGS) -o matrix_class5 matrix_class5.cpp

clean:
	rm -f ./matrix_class1
	rm -f ./matrix_class3
	rm -f ./matrix_class5
